name: Generate docs

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: Install Roc
        uses: hasnep/setup-roc@f1f8d74d6b48104216ebb0556043f44a8729889c # ratchet:hasnep/setup-roc@main
        with:
          roc-version: nightly
      - name: Generate docs
        run: roc docs src/main.roc
      - name: Fix absolute paths
        run: |
          find generated-docs/ -type f -name '*.html' -exec sed -i "s/\(href\|src\)=\"\//\1=\"\/${{ github.event.repository.name }}\//g" {} +
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # ratchet:actions/upload-pages-artifact@v3
        with:
          path: generated-docs
      - name: Deploy docs
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # ratchet:actions/deploy-pages@v4
