name: Test

on:
  # Run on all PRs
  pull_request:
    paths-ignore:
      - "**.md"
  # Run when a PR is merged into main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Install Roc
        uses: hasnep/setup-roc@03aed6eabc3ffd5c367d9d5291a6504a1afd0413 # ratchet:hasnep/setup-roc@v0.1.0
        with:
          roc-version: nightly
      - name: Test the library
        run: roc test src/main.roc
      - name: Run the examples
        run: find examples -name '*.roc' -exec roc run {} \;
